src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cette adresse e-mail.')]
#[ORM\EntityListeners(['App\EntityListener\UserListener'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 46)]
    #[Assert\NotNull()]
    private ?string $lastname = null;

    #[ORM\Column(length: 46)]
    #[Assert\NotNull()]
    private ?string $firstname = null;

    #[ORM\Column(length: 62, unique: true)]
    #[Assert\Email()]
    #[Assert\NotNull()]
    private ?string $email = null;

    #[ORM\Column(length: 25)]
    #[Assert\NotNull()]
    private ?string $phone = null;

    #[ORM\Column(length: 35)]
    #[Assert\NotNull()]
    private ?string $city = null;
    
    private ?string $plain_password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\NotNull()]
    private ?string $password = 'password';

    #[ORM\Column(type: 'datetime')]
    #[Assert\NotNull()]
    private \DateTime $create_at;

    #[ORM\Column(type:'json')]
    #[Assert\NotNull()]
    private array $roles = [];

   
    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Notice::class, orphanRemoval: true)]
    private Collection $notices;

    public function __construct()
    {
        $this->create_at = new \DateTime();
        $this->notices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPlainPassword() 
    {
        return $this->plain_password;
    }

    public function setPlainPassword($plain_password) 
    {
        $this->plain_password = $plain_password;
        return $this;
    }

    public function getCreateAt() 
    {
        return $this->create_at;
    }

    public function setCreateAt($create_at) 
    {
        $this->create_at = $create_at;
        return $this;
    }


    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Notice>
     */
    public function getNotices(): Collection
    {
        return $this->notices;
    }

    public function addNotice(Notice $notice): self
    {
        if (!$this->notices->contains($notice)) {
            $this->notices->add($notice);
            $notice->setUser($this);
        }

        return $this;
    }

    public function removeNotice(Notice $notice): self
    {
        if ($this->notices->removeElement($notice)) {
            // set the owning side to null (unless already changed)
            if ($notice->getUser() === $this) {
                $notice->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/MealType.php
<?php

namespace App\Form;

use App\Entity\Meal;
use App\Entity\Agency;
use App\Repository\AgencyRepository;
use App\Entity\Category;
use App\Repository\CategoryRepository;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class MealType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr'=> [
                    'placeholder' => 'Nom du plat',
                    'class' => 'form-name-meal'
                ],
                'label' => 'Nom du plats',
                'label_attr' => [
                    'class' => 'form-label-meal'
                ],
                'constraints' => [
                    //Valide qu'une valeur n'est pas vide ≠ de chaîne * @Vich\Uploadable
                    new Assert\Length(['min'=> '2' ,'max'=> '75']),
                    new Assert\NotBlank()
                ]  
            ])
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image du plat',
                'required' => false,
                'label_attr' => [
                    'class' => 'form-label'
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr'=> [
                    'placeholder' => 'Description du plat',
                    'class' => 'form-desc-meal'
                ],
                'label' => 'Description du plats',
                'label_attr' => [
                    'class' => 'form-label-meal'
                ],
                'constraints' => [
                    //Valide qu'une valeur n'est pas vide ≠ de chaîne * @Vich\Uploadable
                    new Assert\Length(['min'=> '50'],),
                    new Assert\NotBlank()
                ]  
            ])
            ->add('price', MoneyType::class, [
                'attr'=> [
                    'placeholder' => 'Prix du plat',
                    'class' => 'form-price-meal'
                ],
                'label' => 'Prix',
                'label_attr' => [
                    'class' => 'form-label-meal'
                ],
                'constraints' => [
                    //Valide qu'une valeur n'est pas vide ≠ de chaîne * @Vich\Uploadable
                    new Assert\NotBlank()
                ]  
            ])
            ->add('calorie', NumberType::class, [
                'attr'=> [
                    'placeholder' => 'Calorie du plat (facultatif)',
                    'class' => 'form-calorie-meal'
                ],
                'required' => false,
                'label' => 'Calorie',
                'label_attr' => [
                    'class' => 'form-label-meal'
                ]
            ])
            ->add('id_agency', EntityType::class, [
                'class' => Agency::class,
                // Creation d'une query_builder
                'query_builder' => function(AgencyRepository $r){
                    return $r->createQueryBuilder('i')->orderBy('i.name', 'ASC');
                },
                'placeholder' => 'Choissisez un restaurant',
                'label' => 'Restaurant',
                'choice_label' => 'name'
            ])
            ->add('id_category', EntityType::class, [
                'class' => Category::class,
                'query_builder' => function(CategoryRepository $r){
                    return $r->createQueryBuilder('i')->orderBy('i.name', 'ASC');
                },
                'label' => 'Categorie(s)',
                'choice_label' => 'name',
                'multiple' => true, 
                'expanded' => true,
                'by_reference' => false
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-submit'
                ],
                'label' => 'Créer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Meal::class,
        ]);
    }
}

src/Controller/MealController.php
<?php

namespace App\Controller;

use App\Entity\Meal;
use App\Entity\Notice;
use App\Form\MealType;
use App\Form\NoticeType;
use App\Form\SearchType;
use App\Model\SearchData;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\MealRepository;
use App\Repository\NoticeRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\Post\PostRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class MealController extends AbstractController
{
    /**
     * This controller display all meal
     * @param MealRepository $repository
     * @return Response
     */
    #[Route('/plats', name: 'app_meal', methods:['GET', 'POST'])]
    public function index(
        MealRepository $repository, 
        PaginatorInterface $paginator, 
        Request $request): Response
    {
        /**
         * Setting up the pagination system
         */
        $meal = $paginator->paginate(
            $repository->findAll(), /* query all meals result */
            $request->query->getInt('page', 1), /*page number*/
            12 /*limit per page*/
        );
 
        $searchData = new SearchData();
        $form = $this->createForm(SearchType::class, $searchData);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) 
        {
            //De mettre la request query à getInt
            $searchData->page = $request->query->getInt('page', 1);

            $mealsSearch = $repository->findBySearch($searchData);

            return $this->render("pages/meal/index.html.twig", [
                "form" => $form->createView(),
                "meals" => $mealsSearch
            ] );
        }
        return $this->render('pages/meal/index.html.twig', [
            'form' => $form->createView(),
            'meals' => $meal
        ]);
    }

    /**
     * This controller for create meal
     * 
     */
    #[Security("is_granted('ROLE_ADMIN')")]
    #[Route('/plats/creation', 'meal.new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $meal = new Meal();
        $form = $this->createForm(MealType::class, $meal);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) { 

            $meal = $form->getData();
            $manager->persist($meal);
            $manager->flush();

            $this->addFlash(
                'success',
                'Le plat a été inséré avec succès!'
            );
            return $this->redirectToRoute('app_meal');
        } 
        else {
            $this->addFlash(
                'warning',
                'Le plat n\'a pas pu être inséré !'
            );
        }
        return $this->render('pages/meal/createMeal.html.twig', [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * This controller is for edit a meal 
     * 
     */
    #[Security("is_granted('ROLE_ADMIN')")]
    #[Route('/plats/modification/{id}', name:'meal.edit', methods:['GET', 'POST'])]
    public function editMeal(Meal $meal, Request $request, EntityManagerInterface $manager): Response {

        $form = $this->createForm(MealType::class, $meal);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) { 
            $meal = $form->getData();
            $manager->persist($meal);
            $manager->flush();

            $this->addFlash(
                'success',
                'Le plat a bien été modifié avec succès !'
            );

            return $this->redirectToRoute('app_meal');
        }
        return $this->render('pages/meal/editMeal.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * This controller is for delete a meal
     * 
     */
    #[Security("is_granted('ROLE_ADMIN')")]
    #[Route('/plats/suppression/{id}', name:'meal.delete', methods:['GET'])]
    public function deleteMeal(Meal $meal, Request $request, EntityManagerInterface $manager): Response {
        if(!$meal) {

            $this->addFlash(
                'warning',
                'Le plat n\'a pas été trouvé !'
             );
            return $this->redirectToRoute('app_meal');
        }
        $manager->remove($meal);
        $manager->flush();


        $this->addFlash(
            'delete',
            'Le plat a été supprimé avec succès !'
         );
 
         return $this->redirectToRoute('app_meal');
    }

    #[Route('/plats/{id}', name: 'meal.see', methods:['GET', 'POST'])]
    public function see(
        Meal $meal,
        Request $request, 
        NoticeRepository $noticeRepository, 
        EntityManagerInterface $manager
        ): Response 
    {
        $notice = new Notice();
        $form = $this->createForm(NoticeType::class, $notice);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            // We tell him that the user is the connected user and that 
            // the meal is the one on the page
            $notice->setUser($this->getUser())
                ->setMeal($meal);
            // We will come and test if the user has not already voted
            $existing_notice = $noticeRepository->findOneBy([
                'user' => $this->getUser(),
                'meal' => $meal
            ]);
            /** If $existing_notice is null we persist the data in database
             *  Else 
            */
            if(!$existing_notice){
                $manager->persist($notice);
            } else {
                $existing_notice->setRating(
                    $form->getData()->getRating()
                );
                $existing_notice->setComment(
                    $form->getData()->getComment()
                );
            }
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre vote a bien été pris en compte, nous vous remercions.'
            );
            // If all is well, redirect to the same route
            return $this->redirectToRoute('meal.see', ['id' => $meal->getId()]);
        }

        return $this->render('pages/meal/meal.html.twig', [
            'meal' => $meal,
            'notice' => $notice,
            'form' => $form->createView()
        ]);
    }
}

templates/pages/meal/createMeal.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <div class="container block-dashboard">

        <div class="section-dashboard">
            <div class="menu-dashboard">
                <p><a href="{{ path('user.dashboard', {id : app.user.id}) }}">Mon compte</a></p>

                {% if is_granted('ROLE_ADMIN')%}
                    <p><a href="{{ path('meal.new') }}">Ajouter un plat</a></p>
                    <p><a href="{{ path('app_agency') }} ">Les restaurants</a></p>
                    <p><a href="{{ path('app_category') }}">Les categories</a></p>
                {% endif %}

                <p><a href="{{ path('user.edit', {id : app.user.id}) }}">Modifier mes informations</a></p>
                <p><a href="{{ path('user.edit.password', {id : app.user.id}) }}">Modifier mon mot de passe</a></p>
                <p><a href="{{ path("security.logout") }}">Déconnexion</a></p>
            </div>
            <div class="content-dashboard">

                <h1>Création d'un plats</h1>

               <form class="meal" name="meal" method="post" enctype="multipart/form-data">
                    <div class="create-meal">
                        <div class="col">
                            {{ form_widget(form.name )}}
                            <div class="form-error">
                                {{ form_errors(form.name) }}
                            </div>
                        </div>
                        <div class="col">
                            {{ form_widget(form.imageFile )}}
                            <div class="form-error">
                                {{ form_errors(form.imageFile) }}
                            </div>
                        </div>
                        <div class="col">
                            {{ form_widget(form.description )}}
                            <div class="form-error">
                                {{ form_errors(form.description) }}
                            </div>
                        </div>
                        <div class="col-calorie-price">
                            <div class="col price">
                                {{ form_label(form.price)}}
                                {{ form_widget(form.price )}}
                                <div class="form-error">
                                    {{ form_errors(form.price) }}
                                </div>
                            </div>
                            <div class="col calorie">
                                {{ form_label(form.calorie)}}
                                {{ form_widget(form.calorie )}}
                                <div class="form-error">
                                    {{ form_errors(form.calorie) }}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            {{ form_widget(form.id_agency )}}
                            <div class="form-error">
                                {{ form_errors(form.id_agency) }}
                            </div>
                        </div>
                        <div class="col-category">
                            {{ form_widget(form.id_category )}}
                            <div class="form-error">
                                {{ form_errors(form.id_category) }}
                            </div>
                        </div>
                        {{ form_row(form._token) }}
                        <button type="submit" id="meal_submit" name="meal[submit]" class="btn btn-submit">Créer un plat</button>
                    </div>
                </form>
                {% include "components/_message_flash.html.twig" %}

            </div>
        </div>
    </div>

{% endblock %}

templates/pages/meal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Burgerdi - Tous les plats
{% endblock %}

{% block body %}

<div class="banner_top__pages">
    <img src="{{ asset('images/static/meals.jpeg') }}" alt="">
</div>

<div class="container">

     {% include "components/_search.html.twig" with {
              form: form
        } only %}

    {% include "components/_message_flash.html.twig" %}

    {% if meals.getTotalItemCount > 0 %}

        <div class="count">
            <p><span class="bold">{{ meals.getTotalItemCount }} résultat(s)</span> de plat(s) </p>
        </div>

        <div class="all__cards">
            {% for meal in meals %}
                <div class="card">
                    <a href="{{ path('meal.see', {id: meal.id}) }} ">
                        {% if vich_uploader_asset(meal, 'imageFile') %}
                            <img src="{{ vich_uploader_asset(meal, 'imageFile')}}" alt="Image du plat" class="card__image">
                        {% else %}
                            <img src="{{ asset('images/static/no-picture.jpg') }}" alt="No picture" class="card__image">
                        {% endif %}
                        <div class="card__description">
                            <div class="card__description__title">{{ meal.name }}</div>
                            <div class="card__description__location">{{ meal.agency }}</div>
                            <div class="card__description__desc">{{ meal.description | slice(0, 150) ~ '...' }}</div>                   
                            <div class="card__description__date-note">
                                <div class="card__description__date-note__date">{{ meal.createAt | date("d/m/Y", timezone="Europe/Paris") }}</div>
                                <div class="card__description__date-note__note">
                                    {% if meal.average %}
                                        <p>Note: {{ meal.average }}/5</p>
                                    {% else %}
                                        <p>Ø</p>
                                    {% endif %}
                                </div>
                            </div>
                            
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% else %}

        <div class="count">
            <p><span class="bold">{{ meals.getTotalItemCount }} résultat(s)</span> correspondant à votre demande </p>
        </div>

    {% endif %}

    <div class="navigation">
        {{ knp_pagination_render(meals) }}
    </div>

</div>
{% endblock %}

templates/pages/meal/meal.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Burgerdi - {{ meal.name }}
{% endblock %}


{% block body %}

<div class="container">

    {% if is_granted('ROLE_ADMIN') %}
        
        <a href="{{ path('meal.edit', {id: meal.id})}}" class="btn">Modifier</a>
        <a href="{{ path('meal.delete', {id: meal.id})}}" class="btn">Supprimer</a>
    {% endif %}

    <div class="grid-meal">

        <div class="grid-meal__image">
            <img src="{{ vich_uploader_asset(meal, 'imageFile')}}" alt="">
        </div>

        <div class="grid-meal__info-agency">
            <div class="content-info">

                <div class="title-agency">
                    <p>{{ meal.agency }}</p>
                </div>

                <div class="address-agency openss">
                    <p>{{ meal.address }}, {{ meal.city }}</p>
                </div>
                <div class="webite-agency openss">
                    <a href="{{ meal.website }}" target="_blanck">Cliquer ici pour accéder à leur site</a>
                </div>

                <div class="categories-agency openss">
                    <p class="strong">Categorie(s) :</p>
                    {% for category in meal.idCategory %}
                        {% if category.name %}
                            <span>{{ category.name }}</span>
                        {% else %}
                            <p>Pas de catégories</p>
                        {% endif %}
                    {% endfor %}
                    {# <p>{{ meal.categories }}</p> #}
                </div>
                <div class="resume-notices openss">
                    {% if meal.average == null %}
                        <p>Pas de note encore</p>
                    {% else %}
                        <p>Note: {{ meal.average | number_format(1, '.', ',') }}/5</p>
                    {% endif %}

                </div>
            </div>
        </div>

        <div class="grid-meal__info-meal">

            <div class="title-meal">
                <p>{{ meal.name }}</p>
            </div>

            <div class="desc-meal openss">
                <p>{{ meal.description | nl2br }}</p>
            </div>
            <div class="other-info__flex openss">

                <p class="price">Prix : {{ meal.price | number_format(2, '.', ',') }}€ </p>
            
                <p class="calorie">Calorie : {{ meal.calorie | default('Ø') }}kCal </p>     
            </div>
            <div class="date">
                <p><i>Publié le {{ meal.createAt | date("d-m-Y", "Europe/Paris") }}</i></p>
            </div>

        </div>

            {% if app.user %}
                <div class="grid-meal__info-comment openss">
                    <div class="notice">
                        <form name="notice" method="post">
                            <h2>Et toi ? T'en pense quoi ? Dit le nous..</h2>
                            <div class="col-rating">
                                {{ form_widget(form.rating )}}
                                <div class="form-error">
                                    {{ form_errors(form.rating) }}
                                </div>
                            </div>
                            <div class="col-comment">
                                {{ form_widget(form.comment )}}
                                <div class="form-error">
                                    {{ form_errors(form.comment) }}
                                </div>
                            </div>

                            {{ form_row(form._token)}}
                            <div class="submit-comment">
                                <button type="submit" id="notice_Submit" name="notice[Submit]" class="btn">Commenter</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% else %}
                {# L'utilisateur n'est pas connecté #}
                <div class="grid-meal__info-comment openss">
                    <div class="notice">
                        <form name="notice" method="post">
                                <h2>Et toi ? T'en pense quoi ? Dit le nous..</h2>
                                <p>Pour accéder à cette zone secrète, il faut d'abord se connecter à la matrix !</p>

                            <div class="submit-comment">
                                <a href="{{ path('security.login') }}" class="btn">Se connecter</a>
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>

        {% for message in app.flashes('success') %}
            <div class="flash-notice" style="width: fit-content; padding: 1rem 3rem; background-color: #00a600d9; display: flex; justify-content: center; align-items: center; border-radius: 0 20px;">
                {{ message }}
            </div>
        {% endfor %}

        <div class="section-notice">
            <h3 class="notice-title">Les avis du {{ meal.name }}</h3>

            <div class="all-notice">
                {% for notice in meal.notices %}
                    <div class="one-notice">
                        <div class="user-date">
                            <p class="username">{{ notice.user.firstname }} {{ notice.user.lastname | slice(0, 3) }}***</p>
                            <p class="date-created"><i>{{ notice.createdAt | date("d-m-Y H:i", "Europe/Paris") }}</i></p>
                        </div>
                        <div class="comment openss">
                            <p>{{ notice.comment }}</p>
                        </div>
                        <div class="rating openss">
                            <p>{{ notice.user.firstname }} a décidé de mettre un {{ notice.rating }}/5</p>
                        </div>
                        
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}